# Rustfmt configuration
# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

edition = "2021"
max_width = 100
use_small_heuristics = "Max"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_strings = false
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
newline_style = "Unix"